#!/usr/bin/env python
# -*- coding: utf-8 -*-

try:
    from pydub import AudioSegment, playback
    PYDUB_AVAILABLE = True
except ImportError:
    PYDUB_AVAILABLE = False
    print("Warning: pydub or one of its dependencies (audioop/pyaudioop) could not be imported. LocalTalker will not function properly.")

try:
    from io import BytesIO
    from gtts import gTTS
    GTTS_AVAILABLE = True
except ImportError:
    GTTS_AVAILABLE = False
    print("Warning: gtts could not be imported. LocalTalker will not function properly.")

class Talker:
    def __init__(self, language="en"):
        self.language = language

    def __call__(self, to_say):
        """
        Speaks the string/string Generator to_say. If it's a generator
        It speaks via stream_say, if string via say

        Args:
            to_say (str): The string to speak
        """
        if isinstance(to_say, str):
            self.say(to_say, first=True, last=True)
        else: # If not a string, it's a string generator
            self.stream_say(to_say)

    def say(self, to_say, first=False, last=False):
        """
        Speaks the string to_say

        Args:
            to_say (str): The string to speak
            first (bool): Flag for the first message spoken at once
            last (bool): Flag for the last message spoken at once
        """
    
        raise NotImplementedError
    
    def stream_say(self, to_say):
        """
        Speaks the string generated by to_say line by line.
        
        Args:
            to_say (str): The string to speak
        """
        res = ""
        first = True
        for mes in to_say:
            res += mes
            while res.count('\n') >= 1:
                pos = res.find('\n')
                self.say(res[0:pos],first=first)
                res = res[pos+1:]
                first = False
        self.say(res,first=first,last=True)
    
class TerminalTalker(Talker):
    def __init__(self, language="en", prefix="\nAssistant: "):
        super(TerminalTalker, self).__init__(language=language)
        self.prefix = prefix

    def say(self, to_say, first=False, last=False):
        if first: print(self.prefix + to_say)
        else: print(to_say)
        if last: print()

class LocalTalker(Talker):
    def __init__(self, language="en"):
        super(LocalTalker, self).__init__(language=language)
        if not PYDUB_AVAILABLE:
            print("Warning: LocalTalker will output text instead of audio due to missing pydub dependency.")

    def say(self, to_say, first=False, last=False):
        if not PYDUB_AVAILABLE or not GTTS_AVAILABLE:
            # Fallback to printing text if dependencies are not available
            if first: print("\nLocalTalker: " + to_say)
            else: print(to_say)
            if last: print()
            return
            
        try:
            audio = gTTS(to_say,lang=self.language)
            fp = BytesIO()
            audio.write_to_fp(fp)
            fp.seek(0) # Return to start of file
            segment = AudioSegment.from_file(fp,format="mp3")
            playback.play(segment)
        except Exception as e:
            print("Error playing audio: {}".format(e))
            # Fallback to printing text if audio playback fails
            if first: print("\nLocalTalker: " + to_say)
            else: print(to_say)
            if last: print()

if __name__ == "__main__":
    from Chatter import Chatter
    from Listener import Listener
    name = "Pepper"
    swe_intro = "Du är den mänskliga roboten {}. En NAO-modellrobot byggd av Softbank och programmerad av FIA Robotics. Din uppgift är att hålla en intressant konversation med en grupp människor. Du får max svara med två meningar.".format(name)
    eng_intro = "You are the humanoid robot {}. A NAO model robot built by Softbank and programmed by FIA Robotics. Your task is to hold an interesting conversation with a group of humans. You can at most answer with two sentences".format(name)
    chatter = Chatter(swe_intro, stream=True,chat_horison=5,filt_horizon=3,name=name)
    listener = Listener("sv",use_whisper=False,default_mic=False) # Change to 'en' for english
    talker = LocalTalker("sv")
    while(True):
        heard = listener()
        print("Heard: {}".format(heard))
        if heard != "":
            response = chatter(heard)
            talker(response)
